# Site settings
title: Joanna's Data Science Portfolio
description: A website for me to keep track of my learning progress
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://www.linkedin.com/in/joannakhek/

# User settings
username: Joanna Khek
user_description: Hi I am Joanna Khek Cuina from Singapore. I'm currently an AI Apprentice at AI Singapore, where I am immersed in the dynamic field of artificial intelligence. I hold a Master's degree in Statistics from National University of Singapore and a Bachelor's degree in Mathematical Sciences from Nanyang Technological University.
user_passion: My passion lies in leveraging data to solve real-world challenges, and I find great satisfaction in applying statistical insights to drive meaningful outcomes. I am dedicated to staying at the forefront of AI advancements and actively keep myself updated with new technologies and methodologies in the field. I believe in the power of continuous learning and actively seek opportunities to learn from others in the AI and data science community.
user_sign_off: Feel free to connect with me on LinkedIn!

user_title: AI Apprentice
user_country: Singapore
email: joannakhek@gmail.com
linkedin: https://www.linkedin.com/in/joannakhek/
github_username:  joanna-khek


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
