# Site settings
title: Data Science Portfolio
description: A website for me to keep track of my learning progress
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "www.joanna-khek.github.io" 

# User settings
username: Joanna Khek Cuina
user_description: My name is Joanna Khek Cuina and i graduated from Nanyang Technological University Singapore (NTU) with a Bachelor in Mathematical Sciences (Statistics) in 2018. I am an aspiring Data Scientist and i have strong interest in the domain of Machine Learning as well as creating web application such as dashboards. I also enjoy working on a variety of topics such as Natural Language Processing and Image Classification. You can find my linkedin profile [here](https://linkedin.com/in/joannakhek/)
user_title: Aspiring Data Scientist
email: joannakhek@gmail.com
linkedin: https://www.linkedin.com/in/joannakhek/


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
